let language = {
    english: {
        filterPlaceHolder: "Product name",
        resetFiltersButton: "Reset al filters",
        totalBoughtItems: "Total Bought Items",
        promoMessageHeader: "Don't miss today's hot deal !",
        couponPlaceHolder: "enter coupon code",
        couponButton: "Apply coupon",
        invalidCoupon: "Invalid coupon",
        addCartButton: "Add to cart",
        removeCartButton: "Remove from cart",
        footerHeader: "We bring you only the best products that can be randomly generated!",
        footerDisclaimer: "Content from faker.js with images from Lorem Picsum",
        labelForPrice: "Price",
        labelForCategory: "Category",
        labelForFilterCategory: "Category Filter",
        labelForDescription: "Description",
        labelForOldPrice: "Old price",
        labelForNewPrice: "New price",
        labelForShortDescription: "Short Description",
        labelForCoupon: "Add Coupon",
        labelForApplyCoupon: "Apply Coupon",
        labelForLanguage: "Choose a language",
        labelForTitle: "Random Product of the day",
        labelForSecondTitle: "The rest of the products",
        labelForTotalPrice: "Total $",
        labelForRemove: "Remove item",
        labelForAdd: "Add item",
        labelForFilterName: "Name Filter",
        labelForFilterPrice: "Price Filter",
        labelForBackToProdList: "Back",
        labelForName: "Name",
        labelForReset: "Reset All",
        labelForPromotions: "Promotions",
        labelForWinter: "Winter Offer",
        labelForSpring: "Spring Offer",
        labelForAutumn: "Autumn Offer",
        labelForGoToCheckout: "Check out"
    },
    romanian: {
        filterPlaceHolder: "Nume produs",
        resetFiltersButton: "Reseteaza toate filtrele",
        totalBoughtItems: "Numar total produse cumparate",
        promoMessageHeader: "Oferta zile de azi !",
        couponPlaceHolder: "introduceti cupon",
        couponButton: "Aplicati cupon",
        invalidCoupon: "Cupon invalid",
        addCartButton: "Adauga cos cumparaturi",
        removeCartButton: "Scoate cos cumparaturi",
        footerHeader: "Va aducem cele mai bune produse generate aleator!",
        footerDisclaimer: "Continut generat cu faker.js si imagini din Lorem Picsum",
        labelForFilterPrice: "Filtreaza dupa pret",
        labelForPrice: "Pret",
        labelForCategory: "Categorie",
        labelForFilterCategory: "Filtreaza dupa Categorie",
        labelForDescription: "Descriere",
        labelForOldPrice: "Pret vechi",
        labelForNewPrice: "Pret nou",
        labelForShortDescription: "Scurta descriere",
        labelForCoupon: "Adauga un coupon",
        labelForApplyCoupon: "Aplica Coupon",
        labelForLanguage: "Alege limba",
        labelForTitle: "Produsul zilei",
        labelForSecondTitle: "Restul produselor",
        labelForTotalPrice: "Total $",
        labelForRemove: "Scoate din cos",
        labelForAdd: "Adauga in cos",
        labelForFilterName: "Filtreaza dupa nume",
        labelForBackToProdList: "Inapoi",
        labelForName: "Nume",
        labelForReset: "Reseteaza totul",
        labelForPromotions: "Promotii",
        labelForWinter: "Oferta de Iarna",
        labelForSpring: "Oferta de Primavara",
        labelForAutumn: "Oferta de Toamna",
        labelForGoToCheckout: "Finalizeaza Comanda"
    }
}

export default language;
